---
Resources:
  # Instancia EC2
  MyInstance:
      Type: AWS::EC2::Instance
      Properties:
        AvailabilityZone: us-east-1a
        ImageId: ami-0e1acaae246a0caa4
        InstanceType: t3a.micro
        KeyName: 'sqlslave-v'
        SecurityGroupIds: 
          - sg-0a0db9858ce867f6c
        Tags:
          -
            Key: schedule
            Value: ar-office-hours